# docker-compose.yml for AI-Bike-Coach
version: '3.8'
services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: celery -A app.strava.sync worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
  ui:
    build: .
    command: streamlit run ui/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: timescale/timescaledb-postgis:latest-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikecoach
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]
volumes:
  pgdata:
